'use strict'

const test = require('ava')

const teslaImages = require('..')

const { isAllReachable } = require('./util')

test('Model S 2013', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: [
      'AD02',
      'AF00',
      'AU01',
      'BC0B',
      'BP00',
      'BR00',
      'BT60',
      'CH01',
      'CW00',
      'DA00',
      'DRLH',
      'DV2W',
      'FG00',
      'HP00',
      'IDPB',
      'IPBT',
      'IX00',
      'LP00',
      'MDLS',
      'PA00',
      'PF00',
      'PK01',
      'PMSS',
      'PS01',
      'REEU',
      'RFBC',
      'SC01',
      'SP01',
      'SU01',
      'TM00',
      'TP01',
      'TR00',
      'UTMF',
      'WT19',
      'X001',
      'X003',
      'X007',
      'X011',
      'X013',
      'X020',
      'X025'
    ]
  })

  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S 2014', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: [
      'ADPX2',
      'AF00',
      'APD0',
      'APH0',
      'AU00',
      'BC0B',
      'BP00',
      'BR05',
      'BS00',
      'BT85',
      'CH01',
      'COBE',
      'CW00',
      'DA00',
      'DRLH',
      'DV2W',
      'EUSB',
      'FG01',
      'IDLW',
      'IPMT',
      'IX00',
      'LP00',
      'LT1T',
      'MDLS',
      'ME02',
      'MT85R',
      'PA00',
      'PF00',
      'PK01',
      'PMMB',
      'PS00',
      'REEU',
      'RFPO',
      'S02T',
      'SC04',
      'SP00',
      'SU01',
      'TM00',
      'TP01',
      'TR00',
      'UTMF',
      'WT19',
      'X001',
      'X003',
      'X007',
      'X011',
      'X014',
      'X021',
      'X025',
      'X027',
      'X028',
      'X031',
      'X037',
      'YF00'
    ]
  })

  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S 2015', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: [
      'BP01',
      'ADPX2',
      'AU01',
      'DA02',
      'APH1',
      'APD2',
      'X028',
      'BTX4',
      'PX4D',
      'BS00',
      'BC0R',
      'CH00',
      'CW02',
      'COFR',
      'X039',
      'IDCF',
      'X027',
      'DRLH',
      'AF00',
      'FG02',
      'DCF0',
      'X007',
      'X011',
      'PI01',
      'IX01',
      'X001',
      'LP01',
      'X037',
      'MDLS',
      'DV4W',
      'X024',
      'X003',
      'PPSW',
      'PA00',
      'PS01',
      'PK00',
      'X031',
      'PX00',
      'PF01',
      'TM00',
      'BR01',
      'REEU',
      'RFBC',
      'X014',
      'ME02',
      'QNEB',
      'SR01',
      'SP01',
      'X019',
      'SC04',
      'SU01',
      'TP03',
      'TR00',
      'DSH7',
      'MT90L',
      'UTAB',
      'WTSG',
      'YF00',
      'CPF1'
    ]
  })

  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S 2016', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: [
      'BP00',
      'ADPX2',
      'AU00',
      'DA02',
      'APH1',
      'APD2',
      'X028',
      'BTX4',
      'BS00',
      'BC0B',
      'CH04',
      'CF01',
      'CW00',
      'CODE',
      'X039',
      'IDCF',
      'X027',
      'DRLH',
      'AF02',
      'FG02',
      'DCF0',
      'X007',
      'X011',
      'PI01',
      'IX01',
      'X001',
      'LP01',
      'MI01',
      'X037',
      'MDLS',
      'DV4W',
      'X025',
      'X003',
      'PPMR',
      'PA00',
      'PS01',
      'PK00',
      'X031',
      'PX00',
      'PF00',
      'TM00',
      'BR00',
      'REEU',
      'RFP2',
      'X014',
      'ME02',
      'QNEB',
      'SR01',
      'SP01',
      'X021',
      'SC04',
      'SU01',
      'TP03',
      'TR00',
      'DSH7',
      'MT90A',
      'UTAB',
      'WTAS',
      'YF01',
      'CPF1'
    ]
  })
  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S 2017', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: [
      'ADPX2',
      'AF02',
      'APF2',
      'APH3',
      'APPF',
      'AU01',
      'BCMB',
      'BP02',
      'BR00',
      'BS00',
      'BTX6',
      'CF00',
      'CH04',
      'COFR',
      'CPF1',
      'CW02',
      'DCF0',
      'DRLH',
      'DSH5',
      'DU00',
      'DV4W',
      'FG02',
      'FMP6',
      'FR04',
      'IDBO',
      'INBPP',
      'IX00',
      'LP01',
      'MDLS',
      'ME02',
      'MI01',
      'MT10A',
      'PF00',
      'PI01',
      'PK00',
      'PPSW',
      'PS01',
      'PX00',
      'QTPP',
      'REEU',
      'RFP2',
      'S32P',
      'SC04',
      'SP01',
      'SR07',
      'SU01',
      'TM00',
      'TR00',
      'UTSB',
      'WTAS',
      'X001',
      'X003',
      'X007',
      'X011',
      'X014',
      'X021',
      'X025',
      'X027',
      'X028',
      'X031',
      'X037',
      'X039',
      'X043',
      'YFCC'
    ]
  })

  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S 2018', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: [
      'BP02',
      'ADPX2',
      'AU00',
      'APF2',
      'APH3',
      'APPF',
      'X028',
      'BTX6',
      'BS00',
      'BCMB',
      'CH04',
      'CF00',
      'CW00',
      'COFR',
      'X039',
      'IDBO',
      'X027',
      'DRLH',
      'DU00',
      'AF00',
      'FMP6',
      'FG02',
      'DCF0',
      'FR04',
      'X007',
      'X011',
      'INLFP',
      'PI00',
      'IX00',
      'X001',
      'LP01',
      'MI03',
      'X037',
      'MDLS',
      'DV4W',
      'X025',
      'X003',
      'PMNG',
      'PS01',
      'PK00',
      'X031',
      'PX00',
      'PF00',
      'X043',
      'TM00',
      'BR00',
      'REEU',
      'RFP2',
      'X014',
      'ME02',
      'QTFP',
      'SR07',
      'SP01',
      'X021',
      'SC04',
      'SU01',
      'TR00',
      'TIM3',
      'DSHG',
      'MT10A',
      'UTZW',
      'WTAS',
      'YFCC',
      'CPF1'
    ]
  })

  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S 2019', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: [
      'BP01',
      'ADPX2',
      'AU01',
      'APF2',
      'APH4',
      'APPF',
      'X028',
      'BTX6',
      'PX6D',
      'BS00',
      'BC0R',
      'CH09',
      'CF00',
      'CW02',
      'COFR',
      'X039',
      'IDCF',
      'X027',
      'DRLH',
      'AF02',
      'FMP6',
      'FG02',
      'DCF0',
      'FR04',
      'X007',
      'X011',
      'PI01',
      'IX00',
      'X001',
      'LP01',
      'MI04',
      'X037',
      'MDLS',
      'DV4W',
      'X024',
      'X003',
      'PPMR',
      'PS01',
      'PK00',
      'X031',
      'PX00',
      'PF01',
      'X043',
      'TM00',
      'BR00',
      'REEU',
      'RFFR',
      'X014',
      'ME02',
      'QTFP',
      'SR07',
      'SP01',
      'X019',
      'SC04',
      'SU03',
      'TR00',
      'DSHG',
      'MT10L',
      'UTSB',
      'WTTC',
      'YFCC',
      'CPF0'
    ]
  })

  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S 2020', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: [
      'MDLS',
      'REEU',
      'COAT',
      'GLTL',
      'BTX9',
      'PX6D',
      'EUSB',
      'DV4W',
      'DSHG',
      'PK00',
      'PP01',
      'TD00',
      'FR05',
      'PI01',
      'RFFR',
      'PMNG',
      'IDCF',
      'UTSB',
      'WTAS',
      'FMP6',
      'FG02',
      'LLP2',
      'AF02',
      'LP01',
      'BP01',
      'BR00',
      'BS00',
      'CDM0',
      'DCF2',
      'CH09',
      'CF00',
      'CW02',
      'AU01',
      'ME02',
      'MI04',
      'DRLH',
      'HP00',
      'PS01',
      'PF01',
      'LT6P',
      'S42P',
      'APBS',
      'APFB',
      'APH4',
      'SC04',
      'SP01',
      'SR07',
      'ST01',
      'SU03',
      'YFCC',
      'TIM9',
      'TM00',
      'TR00',
      'WR02',
      'ZINV',
      'X001',
      'X003',
      'X007',
      'X011',
      'X014',
      'X019',
      'X024',
      'X027',
      'X028',
      'X031',
      'X037',
      'X043',
      'X039',
      'ADPX2',
      'FDU2',
      'RDU2',
      'CPF1',
      'FBBR',
      'RBMR',
      'MTS06',
      'INBC3P',
      'ACL1'
    ]
  })

  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S 2021', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: [
      'MDLS',
      'REEU',
      'COIE',
      'GLTL',
      'BTXA',
      'EUSB',
      'DV4W',
      'DSHG',
      'PK00',
      'PP01',
      'TD00',
      'FR05',
      'PI01',
      'RFFR',
      'PMNG',
      'IDBA',
      'UTSB',
      'WTTC',
      'FMP6',
      'FG02',
      'LLP2',
      'AF02',
      'LP01',
      'BP02',
      'BR00',
      'BS00',
      'CDM0',
      'DCF2',
      'CH09',
      'CF00',
      'CW02',
      'AU01',
      'ME01',
      'MI04',
      'DRRH',
      'HP00',
      'PS01',
      'PF00',
      'LT5W',
      'S42W',
      'APBS',
      'APFB',
      'APH4',
      'SC04',
      'SP01',
      'SR07',
      'ST01',
      'SU03',
      'YFCC',
      'TIC6',
      'TM00',
      'TR00',
      'WR02',
      'ZINV',
      'X001',
      'X003',
      'X007',
      'X011',
      'X014',
      'X021',
      'X025',
      'X027',
      'X028',
      'X031',
      'X037',
      'X043',
      'X039',
      'ADPX2',
      'FDU2',
      'RDU4',
      'CPF1',
      'FBBB',
      'RBMB',
      'PWS0',
      'MTS07',
      'INB3W'
    ]
  })

  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S Plaid MTS10', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: ['MTS10', 'PPSW', 'WS90', 'IBE00', 'ST0Y']
  })

  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S Plaid MTS11 with IC00', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: [
      'APBS',
      'APF2',
      'APH4',
      'BC00',
      'BR00',
      'BTXB',
      'CH17',
      'COCA',
      'CP00',
      'CPF1',
      'DRLH',
      'DV4W',
      'FD03',
      'FR05',
      'HL00',
      'IBC00',
      'IC00',
      'ID02',
      'MDLS',
      'MS06',
      'MTS11',
      'PPMR',
      'RD04',
      'RENA',
      'RL00',
      'SC04',
      'ST0Y',
      'SU03',
      'TM00',
      'TR00',
      'TS91',
      'TW00',
      'USSB',
      'WS90',
      'X011',
      'X013',
      'X024',
      'ZINV'
    ]
  })

  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S Plaid MTS11 with ICW00', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: [
      'MDLS',
      'RENA',
      'COUS',
      'BTXB',
      'USSB',
      'DV4W',
      'FR05',
      'PPSB',
      'ID03',
      'WS10',
      'BR00',
      'CH17',
      'MS06',
      'DRLH',
      'APBS',
      'APF2',
      'APH4',
      'SC04',
      'ST0Y',
      'SU03',
      'TS10',
      'TM00',
      'TR00',
      'ZINV',
      'X011',
      'X013',
      'X024',
      'FD03',
      'RD04',
      'CPF0',
      'HL00',
      'RL00',
      'IC02',
      'BC00',
      'TW00',
      'CP00',
      'MTS11',
      'ICW00'
    ]
  })

  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})

test('Model S Ultra Red', async t => {
  const photos = teslaImages({
    modelLetter: 's',
    optionCodes: ['MTS13', 'PR01', 'WS91', 'IBE00', 'ST03']
  })
  console.log(photos)
  t.true(await isAllReachable(photos))
  t.snapshot(photos)
})
