'use strict'

const VIEW_ANGLES = ['STUD_3QTR', 'STUD_SEAT']

const VIEW_ANGLES_OLD = [
  'STUD_3QTR',
  // 'STUD_SEAT_3QTR',
  // 'STUD_SEAT_ABOVE'
  // 'STUD_SIDE',
  // 'STUD_REAR',
  'STUD_SEAT_ALTA'
]

const VIEW_ANGLES_V2 = ['STUD_3QTR_V2', 'STUD_SEAT_V2']

// 'STUD_3QTR', 'STUD_SIDE', 'STUD_REAR', 'STUD_SEAT_ALTA'
// const VIEW_ANGLES_V2 = ['STUD_3QTR_V2', 'STUD_WHEEL_V2', 'STUD_SEAT_V2']

const PAINT_CODES = ['PBSB', 'PMNG', 'PMSS', 'PPMR', 'PPSB', 'PPSW']

const M3_GENERIC_CODES = ['MT3', 'W3', 'W4']

const M3_INTERIOR_CODES = [
  'IN3B2',
  'IN3BB',
  'IN3BW',
  'IN3PB',
  'IN3PW',
  'INB3C',
  'INB3P',
  'INBBP',
  'INBBW',
  'INBC3P',
  'INBC3W',
  'INBCW',
  'INBFP',
  'INBFW',
  'INBLB',
  'INBLW',
  'INBP3P',
  'INBP3W',
  'INBPB',
  'INBPC',
  'INBPP',
  'INBPW',
  'INBTB',
  'INBWS',
  'INFBP',
  'INLFC',
  'INLFP',
  'INLPC',
  'INLPP',
  'INPTB',
  'INWLT',
  'INWPB',
  'INWPT',
  'INYPB',
  'INYPW',
  'IPB0',
  'IPB1',
  'IPW0',
  'IPW1',
  'IVBPP',
  'IVBSW',
  'IVBTB',
  'IVLPC',
  'QPBT',
  'QPMB',
  'QPMG',
  'QPMT',
  'QPMW',
  'QTFC',
  'QTFP',
  'QTFW',
  'QTPB',
  'QTPC',
  'QTPP',
  'QTPT',
  'QTPW',
  'QTSW',
  'QTTB',
  'QTVB',
  'QTVT',
  'QTWS',
  'QXMB',
  'QXMG',
  // new!
  'IBB0',
  'IBB1',
  'IBW0',
  'IBW1'
]

const M3_INTERIOR_DEFAULT = 'IN3PB'

const MY_GENERIC_OPTIONS_CODES = ['MTY', 'WY1', 'WY2']

const MY_INTERIOR_CODES = ['IN']

module.exports = {
  VIEW_ANGLES,
  VIEW_ANGLES_OLD,
  VIEW_ANGLES_V2,
  M3_INTERIOR_CODES,
  M3_INTERIOR_DEFAULT,
  M3_OPTIONS_CODES: M3_GENERIC_CODES.concat(PAINT_CODES, M3_INTERIOR_CODES),
  MY_OPTIONS_CODES: MY_GENERIC_OPTIONS_CODES.concat(
    PAINT_CODES,
    MY_INTERIOR_CODES
  ),
  M3_GENERIC_CODES
}
